.TH "pi_mcp2515_t" 3 "piMCP2515" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pi_mcp2515_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBspi_channel\fP"
.br
.ti -1c
.RI "uint8_t \fBcs_pin\fP"
.br
.ti -1c
.RI "uint8_t \fBtx_pin\fP"
.br
.ti -1c
.RI "uint8_t \fBrx_pin\fP"
.br
.ti -1c
.RI "uint8_t \fBsck_pin\fP"
.br
.ti -1c
.RI "uint32_t \fBspi_clock\fP"
.br
.ti -1c
.RI "uint8_t \fBosc_mhz\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for piMCP2515 from the source code\&.
