.TH "pi_mcp2515_can_frame_t" 3 "piMCP2515" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pi_mcp2515_can_frame_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBid\fP"
.br
.ti -1c
.RI "uint8_t \fBdlc\fP"
.br
.ti -1c
.RI "uint8_t \fBpayload\fP [8]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for piMCP2515 from the source code\&.
